plugins {
    id 'java'
}

version = '1.0'

repositories {
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven { url 'https://www.jitpack.io' }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly "com.github.Anuken.Arc:arc-core:v159"
    compileOnly "com.github.Anuken.Mindustry:core:v159"
}

sourceSets {
    main {
        resources {
            srcDirs = []
        }
    }
}

jar {
    archiveFileName = 'tianyou-shield.jar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from('mod.hjson')
    from('assets') {
        into 'assets'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}
