plugins {
    id 'java'
}

group = 'tianyou.shield'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly "com.github.Anuken.Mindustry:core:v159.7"
    compileOnly "com.github.Anuken.Arc:arc-core:v159.7"
    compileOnly "com.github.Anuken.Arc:flabel:v159.7"
    compileOnly "com.github.Anuken.Arc:freetype:v159.7"
    compileOnly "com.github.Anuken.Arc:g3d:v159.7"
    compileOnly "com.github.Anuken.Arc:arcnet:v159.7"
}

sourceSets {
    main {
        resources {
            srcDirs = []
        }
    }
}

jar {
    archiveFileName = 'tianyou-shield.jar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from('mod.hjson')
    from('assets') {
        into 'assets'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}
